eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:5001/eureka

server:
  port: 7001
  servlet:
    context-path: /resource

spring:
  application:
    name: resource-server
  redis:
    host: 127.0.0.1
    database: 0
    port: 6380
    #password: 123456
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/resource?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

#client-id、client-secret 要和认证服务中的配置一致
#security:
#  oauth2:
#    client:
#      client-id: code-client
#      client-secret: code-client-8888
#      user-authorization-uri: http://localhost:6001/oauth/authorize #授权码模式需要
#      access-token-uri: http://localhost:6001/oauth/token
#    resource:
#      jwt:
#        key-uri: http://localhost:6001/oauth/token_key
#        key-value: dev
#      id: order-client
#    authorization:
      #当此服务端接收到请求后，需要拿着请求中的 token 到认证服务器做 token 验证，就是请求的这个接口
      #check-token-access: http://localhost:6001/oauth/check_token

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
